import type { UserConfig } from "vite-plus";

type LintConfig = NonNullable<UserConfig["lint"]>;
type LintRules = NonNullable<LintConfig["rules"]>;

export const reviewedBaseRules: LintRules = {
  "accessor-pairs": "error",
  "array-callback-return": "error",
  "arrow-body-style": "error",
  curly: ["error", "multi-line", "consistent"],
  "default-case-last": "error",
  "default-param-last": "error",
  eqeqeq: "error",
  "func-name-matching": "error",
  "func-names": "error",
  "grouped-accessor-pairs": ["error", "getBeforeSet"],
  "guard-for-in": "error",
  "import/consistent-type-specifier-style": "error",
  "import/first": "error",
  "import/newline-after-import": "error",
  "import/no-duplicates": "error",
  "import/no-mutable-exports": "error",
  "import/no-named-default": "error",
  "logical-assignment-operators": "error",
  "max-depth": ["error", { max: 3 }],
  "max-nested-callbacks": ["error", { max: 3 }],
  "max-params": ["error", { max: 3 }],
  "no-array-constructor": "error",
  "no-await-in-loop": "error",
  "no-case-declarations": "error",
  "no-constructor-return": "error",
  "no-else-return": "error",
  "no-extra-label": "error",
  "no-fallthrough": "error",
  "no-implicit-coercion": "error",
  "no-inline-comments": "error",
  "no-inner-declarations": "error",
  "no-label-var": "error",
  "no-labels": "error",
  "no-lone-blocks": "error",
  "no-lonely-if": "error",
  "no-loop-func": "error",
  "no-multi-assign": "error",
  "no-multi-str": "error",
  "no-nested-ternary": "error",
  "no-new-func": "error",
  "no-new-wrappers": "error",
  "no-object-constructor": "error",
  "no-promise-executor-return": "error",
  "no-prototype-builtins": "error",
  "no-redeclare": "error",
  "no-return-assign": "error",
  "no-script-url": "error",
  "no-self-compare": "error",
  "no-template-curly-in-string": "error",
  "no-throw-literal": "error",
  "no-useless-call": "error",
  "no-useless-computed-key": "error",
  "no-useless-return": "error",
  "no-warning-comments": "error",
  "object-shorthand": "error",
  "operator-assignment": "error",
  "oxc/branches-sharing-code": "error",
  "oxc/no-accumulating-spread": "error",
  "oxc/no-map-spread": "error",
  "prefer-arrow-callback": "error",
  "prefer-const": "error",
  "prefer-destructuring": "error",
  "prefer-exponentiation-operator": "error",
  "prefer-named-capture-group": "error",
  "prefer-numeric-literals": "error",
  "prefer-object-has-own": "error",
  "prefer-object-spread": "error",
  "prefer-promise-reject-errors": "error",
  "prefer-regex-literals": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  "promise/no-nesting": "error",
  "promise/no-return-wrap": "error",
  "promise/param-names": "error",
  "promise/prefer-await-to-then": "error",
  "promise/prefer-catch": "error",
  radix: "error",
  "symbol-description": "error",
  "typescript/adjacent-overload-signatures": "error",
  "typescript/array-type": "error",
  "typescript/ban-ts-comment": ["error", { minimumDescriptionLength: 10 }],
  "typescript/ban-tslint-comment": "error",
  "typescript/ban-types": "error",
  "typescript/class-literal-property-style": "error",
  "typescript/consistent-generic-constructors": "error",
  "typescript/consistent-indexed-object-style": "error",
  "typescript/consistent-type-assertions": "error",
  "typescript/consistent-type-exports": "error",
  "typescript/consistent-type-imports": [
    "error",
    { prefer: "type-imports", fixStyle: "separate-type-imports" },
  ],
  "typescript/dot-notation": "error",
  "typescript/method-signature-style": "error",
  "typescript/no-confusing-void-expression": "error",
  "typescript/no-deprecated": "error",
  "typescript/no-empty-interface": "error",
  "typescript/no-inferrable-types": "error",
  "typescript/no-misused-promises": "error",
  "typescript/no-mixed-enums": "error",
  "typescript/no-unnecessary-qualifier": "error",
  "typescript/no-unsafe-argument": "error",
  "typescript/no-unsafe-assignment": "error",
  "typescript/no-unsafe-call": "error",
  "typescript/no-unsafe-function-type": "error",
  "typescript/no-unsafe-member-access": "error",
  "typescript/no-unsafe-return": "error",
  "typescript/only-throw-error": "error",
  "typescript/parameter-properties": "error",
  "typescript/prefer-enum-initializers": "error",
  "typescript/prefer-find": "error",
  "typescript/prefer-for-of": "error",
  "typescript/prefer-function-type": "error",
  "typescript/prefer-includes": "error",
  "typescript/prefer-nullish-coalescing": "error",
  "typescript/prefer-promise-reject-errors": "error",
  "typescript/prefer-readonly": "error",
  "typescript/prefer-reduce-type-parameter": "error",
  "typescript/prefer-regexp-exec": "error",
  "typescript/prefer-return-this-type": "error",
  "typescript/prefer-string-starts-ends-with": "error",
  "typescript/prefer-ts-expect-error": "error",
  "typescript/related-getter-setter-pairs": "error",
  "typescript/restrict-plus-operands": "error",
  "typescript/return-await": "error",
  "typescript/strict-boolean-expressions": "error",
  "typescript/strict-void-return": "error",
  "typescript/switch-exhaustiveness-check": "error",
  "typescript/unified-signatures": "error",
  "unicorn/catch-error-name": "error",
  "unicorn/consistent-assert": "error",
  "unicorn/consistent-date-clone": "error",
  "unicorn/consistent-empty-array-spread": "error",
  "unicorn/consistent-existence-index-check": "error",
  "unicorn/consistent-template-literal-escape": "error",
  "unicorn/custom-error-definition": "error",
  "unicorn/error-message": "error",
  "unicorn/escape-case": "error",
  "unicorn/explicit-length-check": "error",
  "unicorn/explicit-timer-delay": "error",
  "unicorn/filename-case": ["error", { case: "kebabCase" }],
  "unicorn/max-nested-calls": ["error", { max: 5 }],
  "unicorn/new-for-builtins": "error",
  "unicorn/no-array-callback-reference": "error",
  "unicorn/no-array-method-this-argument": "error",
  "unicorn/no-await-expression-member": "error",
  "unicorn/no-console-spaces": "error",
  "unicorn/no-hex-escape": "error",
  "unicorn/no-immediate-mutation": "error",
  "unicorn/no-instanceof-array": "error",
  "unicorn/no-negation-in-equality-check": "error",
  "unicorn/no-new-buffer": "error",
  "unicorn/no-static-only-class": "error",
  "unicorn/no-this-assignment": "error",
  "unicorn/no-typeof-undefined": "error",
  "unicorn/no-unnecessary-array-flat-depth": "error",
  "unicorn/no-unnecessary-array-splice-count": "error",
  "unicorn/no-unnecessary-slice-end": "error",
  "unicorn/no-unreadable-array-destructuring": "error",
  "unicorn/no-unreadable-iife": "error",
  "unicorn/no-useless-collection-argument": "error",
  "unicorn/no-useless-promise-resolve-reject": "error",
  "unicorn/no-useless-switch-case": "error",
  "unicorn/no-useless-undefined": "error",
  "unicorn/no-zero-fractions": "error",
  "unicorn/number-literal-case": "error",
  "unicorn/numeric-separators-style": "error",
  "unicorn/prefer-array-find": "error",
  "unicorn/prefer-array-flat": "error",
  "unicorn/prefer-array-flat-map": "error",
  "unicorn/prefer-array-index-of": "error",
  "unicorn/prefer-array-some": "error",
  "unicorn/prefer-at": "error",
  "unicorn/prefer-bigint-literals": "error",
  "unicorn/prefer-blob-reading-methods": "error",
  "unicorn/prefer-class-fields": "error",
  "unicorn/prefer-classlist-toggle": "error",
  "unicorn/prefer-code-point": "error",
  "unicorn/prefer-date-now": "error",
  "unicorn/prefer-default-parameters": "error",
  "unicorn/prefer-dom-node-append": "error",
  "unicorn/prefer-dom-node-dataset": "error",
  "unicorn/prefer-dom-node-remove": "error",
  "unicorn/prefer-dom-node-text-content": "error",
  "unicorn/prefer-export-from": "error",
  "unicorn/prefer-global-this": "error",
  "unicorn/prefer-import-meta-properties": "error",
  "unicorn/prefer-includes": "error",
  "unicorn/prefer-keyboard-event-key": "error",
  "unicorn/prefer-logical-operator-over-ternary": "error",
  "unicorn/prefer-math-min-max": "error",
  "unicorn/prefer-math-trunc": "error",
  "unicorn/prefer-modern-dom-apis": "error",
  "unicorn/prefer-native-coercion-functions": "error",
  "unicorn/prefer-negative-index": "error",
  "unicorn/prefer-number-coercion": "error",
  "unicorn/prefer-object-from-entries": "error",
  "unicorn/prefer-optional-catch-binding": "error",
  "unicorn/prefer-prototype-methods": "error",
  "unicorn/prefer-reflect-apply": "error",
  "unicorn/prefer-regexp-test": "error",
  "unicorn/prefer-response-static-json": "error",
  "unicorn/prefer-set-has": "error",
  "unicorn/prefer-single-call": "error",
  "unicorn/prefer-spread": "error",
  "unicorn/prefer-string-raw": "error",
  "unicorn/prefer-string-replace-all": "error",
  "unicorn/prefer-string-slice": "error",
  "unicorn/prefer-string-trim-start-end": "error",
  "unicorn/prefer-structured-clone": "error",
  "unicorn/prefer-ternary": ["error", "only-single-line"],
  "unicorn/prefer-type-error": "error",
  "unicorn/relative-url-style": "error",
  "unicorn/require-array-join-separator": "error",
  "unicorn/require-module-attributes": "error",
  "unicorn/require-number-to-fixed-digits-argument": "error",
  "unicorn/switch-case-braces": "error",
  "unicorn/switch-case-break-position": "error",
  "unicorn/text-encoding-identifier-case": "error",
  "unicorn/throw-new-error": "error",
  yoda: "error",
};

export const reviewedReactRules: LintRules = {
  "react/checked-requires-onchange-or-readonly": "error",
  "react/display-name": "error",
  "react/function-component-definition": [
    "error",
    {
      namedComponents: "function-declaration",
      unnamedComponents: ["arrow-function", "function-expression"],
    },
  ],
  "react/hook-use-state": "error",
  "react/jsx-boolean-value": "error",
  "react/jsx-curly-brace-presence": "error",
  "react/jsx-fragments": "error",
  "react/jsx-max-depth": ["error", { max: 6 }],
  "react/jsx-no-constructed-context-values": "error",
  "react/jsx-no-target-blank": "error",
  "react/jsx-no-useless-fragment": "error",
  "react/jsx-pascal-case": "error",
  "react/no-array-index-key": "error",
  "react/no-object-type-as-default-prop": "error",
  "react/no-redundant-should-component-update": "error",
  "react/no-set-state": "error",
  "react/no-unescaped-entities": "error",
  "react/prefer-es6-class": "error",
  "react/rules-of-hooks": "error",
  "react/self-closing-comp": "error",
  "react/state-in-constructor": "error",
};

export const reviewedNodeRules: LintRules = {
  "node/callback-return": "error",
  "node/exports-style": "error",
  "node/global-require": "error",
  "node/no-exports-assign": "error",
  "node/no-mixed-requires": "error",
};

export const reviewedVitestRules: LintRules = {
  "vitest/consistent-each-for": "error",
  "vitest/consistent-test-it": ["error", { fn: "test", withinDescribe: "it" }],
  "vitest/consistent-vitest-vi": "error",
  "vitest/max-nested-describe": ["error", { max: 3 }],
  "vitest/no-alias-methods": "error",
  "vitest/no-duplicate-hooks": "error",
  "vitest/no-identical-title": "error",
  "vitest/no-import-node-test": "error",
  "vitest/no-interpolation-in-snapshots": "error",
  "vitest/no-large-snapshots": "error",
  "vitest/no-mocks-import": "error",
  "vitest/no-test-prefixes": "error",
  "vitest/no-test-return-statement": "error",
  "vitest/no-unneeded-async-expect-function": "error",
  "vitest/padding-around-after-all-blocks": "error",
  "vitest/padding-around-test-blocks": "error",
  "vitest/prefer-called-exactly-once-with": "error",
  "vitest/prefer-called-once": "error",
  "vitest/prefer-called-with": "error",
  "vitest/prefer-comparison-matcher": "error",
  "vitest/prefer-each": "error",
  "vitest/prefer-equality-matcher": "error",
  "vitest/prefer-expect-resolves": "error",
  "vitest/prefer-expect-type-of": "error",
  "vitest/prefer-hooks-in-order": "error",
  "vitest/prefer-hooks-on-top": "error",
  "vitest/prefer-import-in-mock": "error",
  "vitest/prefer-importing-vitest-globals": "error",
  "vitest/prefer-mock-promise-shorthand": "error",
  "vitest/prefer-mock-return-shorthand": "error",
  "vitest/prefer-spy-on": "error",
  "vitest/prefer-strict-boolean-matchers": "error",
  "vitest/prefer-strict-equal": "error",
  "vitest/prefer-to-be": "error",
  "vitest/prefer-to-be-object": "error",
  "vitest/prefer-to-contain": "error",
  "vitest/prefer-to-have-been-called-times": "error",
  "vitest/prefer-to-have-length": "error",
  "vitest/prefer-todo": "error",
};
