import type { Rules } from "../types.ts";

export const eslintRules: Rules = {
  "eslint/no-magic-numbers": "off",
  "eslint/no-unreachable": "warn",
  "eslint/max-params": "warn",
  "eslint/no-console": ["warn", { allow: ["info", "warn", "error"] }],
  curly: "error",
  "default-case-last": "error",
  eqeqeq: "error",
  "grouped-accessor-pairs": "error",
  "no-alert": "error",
  "no-case-declarations": "error",
  "no-constructor-return": "error",
  "no-else-return": "error",
  "no-fallthrough": "error",
  "no-param-reassign": "error",
  "no-prototype-builtins": "error",
  "no-unneeded-ternary": "error",
  "no-useless-return": "error",
  "object-shorthand": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  "no-var": "error",
  "prefer-const": "error",
  "no-misleading-character-class": "error",
  "no-regex-spaces": "error",
  "prefer-rest-params": "error",
};
