import type { OxlintConfig } from "oxlint";
import { defineConfig } from "oxlint";

export const BASE_PLUGINS = ["typescript", "unicorn", "oxc", "import", "promise"] as const;

export const base: OxlintConfig = defineConfig({
  plugins: [...BASE_PLUGINS],
  env: {
    serviceworker: true,
    worker: true,
  },
  options: {
    reportUnusedDisableDirectives: "error",
    typeAware: true,
  },
  categories: {
    correctness: "error",
    suspicious: "error",
    pedantic: "error",
    perf: "error",
    style: "error",
  },
  rules: {
    "func-style": "off",
    "id-length": "off",
    "capitalized-comments": "off",
    curly: ["error", "multi-line", "consistent"],
    "init-declarations": "off",
    "no-magic-numbers": "off",
    "no-ternary": "off",
    "sort-imports": "off",
    "sort-keys": "off",
    "vars-on-top": "off",
    complexity: ["error", { max: 10 }],
    "default-case-last": "error",
    eqeqeq: "error",
    "getter-return": "error",
    "grouped-accessor-pairs": ["error", "getBeforeSet"],
    "max-classes-per-file": ["error", { max: 1 }],
    "max-depth": ["error", { max: 3 }],
    "max-lines-per-function": ["error", { max: 50, skipBlankLines: true, skipComments: true }],
    "import/no-unassigned-import": "off",
    "max-nested-callbacks": ["error", { max: 3 }],
    "max-params": ["error", { max: 3 }],
    "max-statements": ["error", { max: 10 }],
    "no-alert": "error",
    "no-bitwise": "error",
    "no-console": ["error", { allow: ["info", "warn", "error"] }],
    "no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
    "no-param-reassign": ["error", { props: true }],
    "no-plusplus": "error",
    "no-undef": "error",
    "no-unneeded-ternary": "error",
    "no-unreachable": "error",
    "no-useless-return": "error",
    "prefer-template": "error",

    "import/exports-last": "off",
    "import/group-exports": "off",
    "import/no-anonymous-default-export": "off",
    "import/no-named-export": "off",
    "import/no-namespace": "off",
    "import/no-nodejs-modules": "off",
    "import/prefer-default-export": "off",
    "typescript/consistent-type-definitions": "off",
    "import/no-cycle": "error",

    "typescript/ban-ts-comment": ["error", { minimumDescriptionLength: 10 }],
    "typescript/consistent-return": "error",
    "typescript/consistent-type-exports": "error",
    "typescript/consistent-type-imports": [
      "error",
      { prefer: "type-imports", fixStyle: "separate-type-imports" },
    ],
    "typescript/dot-notation": "error",
    "typescript/no-confusing-void-expression": "error",
    "typescript/no-dynamic-delete": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-misused-promises": "error",
    "typescript/no-misused-spread": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-unnecessary-condition": "error",
    "typescript/no-unnecessary-qualifier": "error",
    "typescript/no-unnecessary-type-arguments": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-type-parameters": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/no-useless-default-assignment": "error",
    "typescript/non-nullable-type-assertion-style": "error",
    "typescript/only-throw-error": "error",
    "typescript/prefer-find": "error",
    "typescript/prefer-nullish-coalescing": "error",
    "typescript/prefer-optional-chain": "error",
    "typescript/prefer-readonly": "error",
    "typescript/prefer-readonly-parameter-types": "error",
    "typescript/prefer-regexp-exec": "error",
    "typescript/promise-function-async": "error",
    "typescript/require-array-sort-compare": "error",
    "typescript/restrict-plus-operands": "error",
    "typescript/restrict-template-expressions": "error",
    "typescript/return-await": "error",
    "typescript/strict-boolean-expressions": "error",
    "typescript/strict-void-return": "error",
    "typescript/switch-exhaustiveness-check": "error",
    "typescript/unbound-method": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",

    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-null": "off",
    "unicorn/filename-case": ["error", { case: "kebabCase" }],
  },
  overrides: [
    {
      files: ["**/*.{cjs,cts}"],
      env: {
        node: true,
      },
      rules: {
        "typescript/no-require-imports": "off",
      },
    },
    {
      files: ["**/*.config.{js,jsx,ts,tsx,mjs,cjs,mts,cts}"],
      rules: {
        "func-names": "off",
      },
    },
    {
      files: [
        "**/test/**",
        "**/tests/**",
        "**/__tests__/**",
        "**/*.{test,spec}.{js,jsx,ts,tsx,mjs,cjs,mts,cts}",
      ],
      plugins: [...BASE_PLUGINS, "vitest"],
      env: {
        vitest: true,
      },
      rules: {
        "max-lines-per-function": ["error", { max: 75, skipBlankLines: true, skipComments: true }],
        "vitest/no-importing-vitest-globals": "off",
        "vitest/max-nested-describe": ["error", { max: 3 }],
      },
    },
  ],
});
