import type { LintRules } from "../types.ts";

export const universalRules: LintRules = {
  "accessor-pairs": "error",
  "array-callback-return": "error",
  "arrow-body-style": "error",
  curly: ["error", "multi-line", "consistent"],
  "default-case-last": "error",
  "default-param-last": "error",
  eqeqeq: "error",
  "func-name-matching": "error",
  "func-names": "error",
  "grouped-accessor-pairs": ["error", "getBeforeSet"],
  "guard-for-in": "error",
  "import/consistent-type-specifier-style": "error",
  "import/first": "error",
  "import/newline-after-import": "error",
  "import/no-duplicates": "error",
  "import/no-mutable-exports": "error",
  "import/no-named-default": "error",
  "logical-assignment-operators": "error",
  "max-depth": [
    "error",
    {
      max: 3,
    },
  ],
  "max-nested-callbacks": [
    "error",
    {
      max: 3,
    },
  ],
  "max-params": [
    "error",
    {
      max: 3,
    },
  ],
  "no-array-constructor": "error",
  "no-await-in-loop": "error",
  "no-case-declarations": "error",
  "no-constructor-return": "error",
  "no-else-return": "error",
  "no-extra-label": "error",
  "no-fallthrough": "error",
  "no-implicit-coercion": "error",
  "no-inline-comments": "error",
  "no-inner-declarations": "error",
  "no-label-var": "error",
  "no-labels": "error",
  "no-lone-blocks": "error",
  "no-lonely-if": "error",
  "no-loop-func": "error",
  "no-multi-assign": "error",
  "no-multi-str": "error",
  "no-nested-ternary": "error",
  "no-new-func": "error",
  "no-new-wrappers": "error",
  "no-object-constructor": "error",
  "no-promise-executor-return": "error",
  "no-prototype-builtins": "error",
  "no-redeclare": "error",
  "no-return-assign": "error",
  "no-script-url": "error",
  "no-self-compare": "error",
  "no-template-curly-in-string": "error",
  "no-throw-literal": "error",
  "no-useless-call": "error",
  "no-useless-computed-key": "error",
  "no-useless-return": "error",
  "no-warning-comments": "error",
  "object-shorthand": "error",
  "operator-assignment": "error",
  "oxc/branches-sharing-code": "error",
  "oxc/no-accumulating-spread": "error",
  "oxc/no-map-spread": "error",
  "prefer-arrow-callback": "error",
  "prefer-const": "error",
  "prefer-destructuring": "error",
  "prefer-exponentiation-operator": "error",
  "prefer-named-capture-group": "error",
  "prefer-numeric-literals": "error",
  "prefer-object-has-own": "error",
  "prefer-object-spread": "error",
  "prefer-promise-reject-errors": "error",
  "prefer-regex-literals": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  "promise/no-nesting": "error",
  "promise/no-return-wrap": "error",
  "promise/param-names": "error",
  "promise/prefer-await-to-then": "error",
  "promise/prefer-catch": "error",
  radix: "error",
  "symbol-description": "error",
  "typescript/adjacent-overload-signatures": "error",
  "typescript/array-type": "error",
  "typescript/ban-ts-comment": [
    "error",
    {
      minimumDescriptionLength: 10,
    },
  ],
  "typescript/ban-tslint-comment": "error",
  "typescript/ban-types": "error",
  "typescript/class-literal-property-style": "error",
  "typescript/consistent-generic-constructors": "error",
  "typescript/consistent-indexed-object-style": "error",
  "typescript/consistent-type-assertions": "error",
  "typescript/consistent-type-exports": "error",
  "typescript/consistent-type-imports": [
    "error",
    {
      prefer: "type-imports",
      fixStyle: "separate-type-imports",
    },
  ],
  "typescript/dot-notation": "error",
  "typescript/method-signature-style": "error",
  "typescript/no-confusing-void-expression": "error",
  "typescript/no-deprecated": "error",
  "typescript/no-empty-interface": "error",
  "typescript/no-inferrable-types": "error",
  "typescript/no-misused-promises": "error",
  "typescript/no-mixed-enums": "error",
  "typescript/no-unnecessary-qualifier": "error",
  "typescript/no-unsafe-argument": "error",
  "typescript/no-unsafe-assignment": "error",
  "typescript/no-unsafe-call": "error",
  "typescript/no-unsafe-function-type": "error",
  "typescript/no-unsafe-member-access": "error",
  "typescript/no-unsafe-return": "error",
  "typescript/only-throw-error": "error",
  "typescript/parameter-properties": "error",
  "typescript/prefer-enum-initializers": "error",
  "typescript/prefer-find": "error",
  "typescript/prefer-for-of": "error",
  "typescript/prefer-function-type": "error",
  "typescript/prefer-includes": "error",
  "typescript/prefer-nullish-coalescing": "error",
  "typescript/prefer-promise-reject-errors": "error",
  "typescript/prefer-readonly": "error",
  "typescript/prefer-reduce-type-parameter": "error",
  "typescript/prefer-regexp-exec": "error",
  "typescript/prefer-return-this-type": "error",
  "typescript/prefer-string-starts-ends-with": "error",
  "typescript/prefer-ts-expect-error": "error",
  "typescript/related-getter-setter-pairs": "error",
  "typescript/restrict-plus-operands": "error",
  "typescript/return-await": "error",
  "typescript/strict-boolean-expressions": "error",
  "typescript/strict-void-return": "error",
  "typescript/switch-exhaustiveness-check": "error",
  "typescript/unified-signatures": "error",
  "unicorn/catch-error-name": "error",
  "unicorn/consistent-assert": "error",
  "unicorn/consistent-date-clone": "error",
  "unicorn/consistent-empty-array-spread": "error",
  "unicorn/consistent-existence-index-check": "error",
  "unicorn/consistent-template-literal-escape": "error",
  "unicorn/custom-error-definition": "error",
  "unicorn/error-message": "error",
  "unicorn/escape-case": "error",
  "unicorn/explicit-length-check": "error",
  "unicorn/explicit-timer-delay": "error",
  "unicorn/filename-case": [
    "error",
    {
      case: "kebabCase",
    },
  ],
  "unicorn/max-nested-calls": [
    "error",
    {
      max: 5,
    },
  ],
  "unicorn/new-for-builtins": "error",
  "unicorn/no-array-callback-reference": "error",
  "unicorn/no-array-method-this-argument": "error",
  "unicorn/no-await-expression-member": "error",
  "unicorn/no-console-spaces": "error",
  "unicorn/no-hex-escape": "error",
  "unicorn/no-immediate-mutation": "error",
  "unicorn/no-instanceof-array": "error",
  "unicorn/no-negation-in-equality-check": "error",
  "unicorn/no-new-buffer": "error",
  "unicorn/no-static-only-class": "error",
  "unicorn/no-this-assignment": "error",
  "unicorn/no-typeof-undefined": "error",
  "unicorn/no-unnecessary-array-flat-depth": "error",
  "unicorn/no-unnecessary-array-splice-count": "error",
  "unicorn/no-unnecessary-slice-end": "error",
  "unicorn/no-unreadable-array-destructuring": "error",
  "unicorn/no-unreadable-iife": "error",
  "unicorn/no-useless-collection-argument": "error",
  "unicorn/no-useless-promise-resolve-reject": "error",
  "unicorn/no-useless-switch-case": "error",
  "unicorn/no-useless-undefined": "error",
  "unicorn/no-zero-fractions": "error",
  "unicorn/number-literal-case": "error",
  "unicorn/numeric-separators-style": "error",
  "unicorn/prefer-array-find": "error",
  "unicorn/prefer-array-flat": "error",
  "unicorn/prefer-array-flat-map": "error",
  "unicorn/prefer-array-index-of": "error",
  "unicorn/prefer-array-some": "error",
  "unicorn/prefer-at": "error",
  "unicorn/prefer-bigint-literals": "error",
  "unicorn/prefer-blob-reading-methods": "error",
  "unicorn/prefer-class-fields": "error",
  "unicorn/prefer-code-point": "error",
  "unicorn/prefer-date-now": "error",
  "unicorn/prefer-default-parameters": "error",
  "unicorn/prefer-export-from": "error",
  "unicorn/prefer-global-this": "error",
  "unicorn/prefer-import-meta-properties": "error",
  "unicorn/prefer-includes": "error",
  "unicorn/prefer-logical-operator-over-ternary": "error",
  "unicorn/prefer-math-min-max": "error",
  "unicorn/prefer-math-trunc": "error",
  "unicorn/prefer-native-coercion-functions": "error",
  "unicorn/prefer-negative-index": "error",
  "unicorn/prefer-number-coercion": "error",
  "unicorn/prefer-object-from-entries": "error",
  "unicorn/prefer-optional-catch-binding": "error",
  "unicorn/prefer-prototype-methods": "error",
  "unicorn/prefer-reflect-apply": "error",
  "unicorn/prefer-regexp-test": "error",
  "unicorn/prefer-response-static-json": "error",
  "unicorn/prefer-set-has": "error",
  "unicorn/prefer-single-call": "error",
  "unicorn/prefer-spread": "error",
  "unicorn/prefer-string-raw": "error",
  "unicorn/prefer-string-replace-all": "error",
  "unicorn/prefer-string-slice": "error",
  "unicorn/prefer-string-trim-start-end": "error",
  "unicorn/prefer-structured-clone": "error",
  "unicorn/prefer-ternary": ["error", "only-single-line"],
  "unicorn/prefer-type-error": "error",
  "unicorn/relative-url-style": "error",
  "unicorn/require-array-join-separator": "error",
  "unicorn/require-module-attributes": "error",
  "unicorn/require-number-to-fixed-digits-argument": "error",
  "unicorn/switch-case-braces": "error",
  "unicorn/switch-case-break-position": "error",
  "unicorn/text-encoding-identifier-case": "error",
  "unicorn/throw-new-error": "error",
  yoda: "error",
  complexity: [
    "error",
    {
      max: 20,
    },
  ],
  "getter-return": "error",
  "no-bitwise": "error",
  "no-console": [
    "error",
    {
      allow: ["info", "warn", "error"],
    },
  ],
  "no-param-reassign": [
    "error",
    {
      props: true,
    },
  ],
  "no-plusplus": "error",
  "no-undef": "error",
  "no-unneeded-ternary": "error",
  "no-unreachable": "error",
  "import/no-cycle": "error",
  "import/no-unassigned-import": "off",
  "oxc/bad-match-all-arg": "error",
  "typescript/consistent-return": "error",
  "typescript/explicit-module-boundary-types": "error",
  "typescript/no-dynamic-delete": "error",
  "typescript/no-explicit-any": "error",
  "typescript/no-floating-promises": "error",
  "typescript/no-misused-spread": "error",
  "typescript/no-non-null-assertion": "error",
  "typescript/no-require-imports": "error",
  "typescript/no-unnecessary-condition": "error",
  "typescript/no-unnecessary-type-arguments": "error",
  "typescript/no-unnecessary-type-assertion": "error",
  "typescript/no-unnecessary-type-parameters": "error",
  "typescript/no-useless-default-assignment": "error",
  "typescript/non-nullable-type-assertion-style": "error",
  "typescript/prefer-optional-chain": "error",
  "typescript/require-array-sort-compare": "error",
  "typescript/restrict-template-expressions": "error",
  "typescript/unbound-method": "error",
  "typescript/use-unknown-in-catch-callback-variable": "error",
  "unicorn/no-abusive-eslint-disable": "error",
};
