import type { LintRules } from "../types.ts";

export const vitestRules: LintRules = {
  "vitest/consistent-each-for": "error",
  "vitest/consistent-test-it": [
    "error",
    {
      fn: "test",
      withinDescribe: "it",
    },
  ],
  "vitest/consistent-vitest-vi": "error",
  "vitest/max-nested-describe": [
    "error",
    {
      max: 3,
    },
  ],
  "vitest/no-alias-methods": "error",
  "vitest/no-duplicate-hooks": "error",
  "vitest/no-identical-title": "error",
  "vitest/no-import-node-test": "error",
  "vitest/no-interpolation-in-snapshots": "error",
  "vitest/no-large-snapshots": "error",
  "vitest/no-mocks-import": "error",
  "vitest/no-test-prefixes": "error",
  "vitest/no-test-return-statement": "error",
  "vitest/no-unneeded-async-expect-function": "error",
  "vitest/padding-around-after-all-blocks": "error",
  "vitest/padding-around-test-blocks": "error",
  "vitest/prefer-called-exactly-once-with": "error",
  "vitest/prefer-called-once": "error",
  "vitest/prefer-called-with": "error",
  "vitest/prefer-comparison-matcher": "error",
  "vitest/prefer-each": "error",
  "vitest/prefer-equality-matcher": "error",
  "vitest/prefer-expect-resolves": "error",
  "vitest/prefer-expect-type-of": "error",
  "vitest/prefer-hooks-in-order": "error",
  "vitest/prefer-hooks-on-top": "error",
  "vitest/prefer-import-in-mock": "error",
  "vitest/prefer-importing-vitest-globals": "error",
  "vitest/prefer-mock-promise-shorthand": "error",
  "vitest/prefer-mock-return-shorthand": "error",
  "vitest/prefer-spy-on": "error",
  "vitest/prefer-strict-boolean-matchers": "error",
  "vitest/prefer-strict-equal": "error",
  "vitest/prefer-to-be": "error",
  "vitest/prefer-to-be-object": "error",
  "vitest/prefer-to-contain": "error",
  "vitest/prefer-to-have-been-called-times": "error",
  "vitest/prefer-to-have-length": "error",
  "vitest/prefer-todo": "error",
};
